[package]
name = "dgdarc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2"
serde = { version = "1.0.203", features = ["serde_derive"] }
toml = "0.8.14"
