level_name = "The beginning"
background_texture = "EvilGrass.png"
points_of_interest = [[[10, 10], "Ground"]]

[[heros]]
hero_type = "JohnHeron"
targets = [[300, 150]]
position = [-100, -100]
speed = 100
max_health = 100
