level_name = "The beginning"
background_texture = "EvilGrass.png"
music = "Battle_1.ogg"
points_of_interest = [[[5, 3], "Chest"], [[3, 1], "Spike"], [[2, 1], "Pole"], [[4, 1], "Pole"], [[4, 2], "Pole"], [[3, 2], "Hole"]]

[[heros]]
hero_type = "JohnHeron"
targets = [[300, 150]]
position = [-100, -100]
speed = 100
max_health = 100
